spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourEmail@gmail.com
    password: yourKey
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true